### ISSUE TITLE
React Native SDK: Android Instructions don't work

### ISSUE THREAD

**Issue by mraible** [okta/okta-oidc-js#561]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [ ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [x] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

I tried following the instructions for this package and I can't get them to work for Android. 

## Expected behavior

I expect the instructions to work and my app to launch. The instructions work for iOS. 

## Minimal reproduction of the problem with instructions

Steps to reproduce:

1. Generate an app with React Native CLI: `react-native init SecureApp`
2. `npm install @okta/okta-react-native`
3. `react-native link @okta/okta-react-native`
4. Add bintray URL to `android/build.gradle` and set `minSdkVersion` to 19
5. Add redirect scheme in `android/app/build.gradle`

When I try to run the app, I get compilation errors:

```
$ react-native run-android
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - @okta/okta-react-native (to unlink run: "react-native unlink @okta/okta-react-native")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1820 file(s) to forward-jetify. Using 12 workers...
info JS server already running.
info Installing the app...

> Configure project :@okta_okta-react-native
WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

> Task :@okta_okta-react-native:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
9 actionable tasks: 9 executed
/Users/mraible/dev/okta/schematics/apps/SecureApp/node_modules/@okta/okta-react-native/android/src/main/java/com/oktareactnative/OktaSdkBridgeModule.java:96: error: cannot find symbol
            this.authClient = new Okta.AuthBuilder()
                ^
  symbol: variable authClient
/Users/mraible/dev/okta/schematics/apps/SecureApp/node_modules/@okta/okta-react-native/android/src/main/java/com/oktareactnative/OktaSdkBridgeModule.java:134: error: cannot find symbol
        if (authClient == null) {
            ^
  symbol:   variable authClient
  location: class OktaSdkBridgeModule
/Users/mraible/dev/okta/schematics/apps/SecureApp/node_modules/@okta/okta-react-native/android/src/main/java/com/oktareactnative/OktaSdkBridgeModule.java:147: error: cannot find symbol
                        SessionClient sessionClient = authClient.getSessionClient();
                                                      ^
  symbol: variable authClient
/Users/mraible/dev/okta/schematics/apps/SecureApp/node_modules/@okta/okta-react-native/android/src/main/java/com/oktareactnative/OktaSdkBridgeModule.java:142: error: cannot find symbol
        authClient.signIn(sessionToken, null, new RequestCallback<Result, AuthorizationException>() {
        ^
  symbol:   variable authClient
  location: class OktaSdkBridgeModule
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':@okta_okta-react-native:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/Users/mraible/dev/okta/schematics/apps/SecureApp/node_modules/@okta/okta-react-native/android/src/main/java/com/oktareactnative/OktaSdkBridgeModule.java:96: error: cannot find symbol
            this.authClient = new Okta.AuthBuilder()
                ^
  symbol: variable authClient
/Users/mraible/dev/okta/schematics/apps/SecureApp/node_modules/@okta/okta-react-native/android/src/main/java/com/oktareactnative/OktaSdkBridgeModule.java:134: error: cannot find symbol
        if (authClient == null) {
            ^
  symbol:   variable authClient
  location: class OktaSdkBridgeModule
/Users/mraible/dev/okta/schematics/apps/SecureApp/node_modules/@okta/okta-react-native/android/src/main/java/com/oktareactnative/OktaSdkBridgeModule.java:147: error: cannot find symbol
                        SessionClient sessionClient = authClient.getSessionClient();
                                                      ^
  symbol: variable authClient
/Users/mraible/dev/okta/schematics/apps/SecureApp/node_modules/@okta/okta-react-native/android/src/main/java/com/oktareactnative/OktaSdkBridgeModule.java:142: error: cannot find symbol
        authClient.signIn(sessionToken, null, new RequestCallback<Result, AuthorizationException>() {
        ^
  symbol:   variable authClient
  location: class OktaSdkBridgeModule
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':@okta_okta-react-native:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

    at checkExecSyncError (child_process.js:629:11)
    at execFileSync (child_process.js:647:13)
    at runOnAllDevices (/Users/mraible/dev/okta/schematics/apps/SecureApp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:74:39)
    at buildAndRun (/Users/mraible/dev/okta/schematics/apps/SecureApp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
    at then.result (/Users/mraible/dev/okta/schematics/apps/SecureApp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Execution time: 5 s.                       
```

I also tried the manual setup and modifying `MainApplication.java`, but that doesn't work either.

## Environment

- Package Version: 1.2.0
- Browser:
- OS: Mac
- Node version (`node -v`): v10.16.0
- Other:

**Comment by mraible** [comment]
I was able to workaround this issue by modifying `node_modules/@okta/okta-react-native/android/src/main/java/com/oktareactnative/OktaSdkBridgeModule.java` and adding `authClient` as a local variable.

```java
private WebAuthClient webClient;
private AuthClient authClient;
```

This allows me to deploy my app onto an AVD. However, when I click Login, it doesn't work:

```
E/SyncWebAuthClientImpl: No uri registered to handle redirect or multiple applications registered
```

I tried wiping the data on my AVD, but that didn't help.

**Comment by IldarAbdullin-okta** [comment]
@mraible , can you confirm that you added `appAuthRedirectScheme` parameter into application's build.gradle file? Can you also confirm that redirect scheme is correct?

@FeiChen-okta , what else can be checked on Android part?

**Comment by FeiChen-okta** [comment]
> @mraible , can you confirm that you added `appAuthRedirectScheme` parameter into application's build.gradle file? Can you also confirm that redirect scheme is correct?
> 
> @FeiChen-okta , what else can be checked on Android part?

The only thing i can think of is to check the instructions for [appAuthRedirectScheme](https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react-native#add-redirect-scheme). Then check if it is correct on the device with the adb command
```bash
adb shell dumpsys package | grep {appAuthRedirectScheme}
```

**Comment by mraible** [comment]
I have an appAuthRedirectScheme configured in `android/app/build.gradle`:

```groovy
    defaultConfig {
        applicationId "com.secureapp"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        manifestPlaceholders = [
            appAuthRedirectScheme: 'com.okta.dev-133320' // com.okta.dev-123456
        ]
    }
```

Using the command, I see:

```
$ adb shell dumpsys package | grep com.okta
      com.okta.dev-133320:
        4e9d592 com.secureapp/com.okta.oidc.OktaRedirectActivity
```

**Comment by mraible** [comment]
It turns out I had a different Okta org for my OIDC settings. Once I changed them to use the same reversed package name in `redirectUri` and `endSessionRedirectUri`, everything works.

**Comment by Dhaval240420** [comment]
`11-15 18:41:54.224 12378 12500 W SyncWebAuthClientImpl: Warning! Multiple applications found registered with same scheme
11-15 18:41:54.224 12378 12500 E SyncWebAuthClientImpl: No uri registered to handle redirect or multiple applications registered`

@mraible can you please help me with this issue i am getting same issue

i check all the things and can not get any solution

**Comment by mraible** [comment]
This tutorial might help: https://developer.okta.com/blog/2019/11/14/react-native-login

**Comment by Dhaval240420** [comment]
> This tutorial might help: https://developer.okta.com/blog/2019/11/14/react-native-login
> […](#)
> On Nov 15, 2019, at 08:17, Dhaval240420 ***@***.***> wrote: ﻿ 11-15 18:41:54.224 12378 12500 W SyncWebAuthClientImpl: Warning! Multiple applications found registered with same scheme 11-15 18:41:54.224 12378 12500 E SyncWebAuthClientImpl: No uri registered to handle redirect or multiple applications registered @mraible can you please help me with this issue i am getting same issue i check all the things and can not get any solution — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

@mraible Thank you for response, this document solved my issue
