### ISSUE TITLE
PROD Build getting failed while using OKTA_CONFIG using latest version OKTA 1.3.0

### ISSUE THREAD

**Issue by krishtgkk** [okta/okta-oidc-js#627]
## I'm submitting this issue for the package(s):

- [ ] jwt-verifier
- [X ] okta-angular
- [ ] oidc-middleware
- [ ] okta-react
- [ ] okta-react-native
- [ ] okta-vue

## I'm submitting a:

- [X ] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

While doing Prod Build App is throwing following error 
ERROR in src\app\app.module.ts(221,16): Error during template compile of 'AppModule'
  Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler in 'OKTA_CONFIG'
    'OKTA_CONFIG' references 'OKTA_CONFIG'
      'OKTA_CONFIG' is not initialized at @okta\okta-angular\dist\src\okta\models\okta.config.ts(24,22).

## Expected behavior

No Errors

## Minimal reproduction of the problem with instructions

ng build --prod

Angular compile version 7+

## Environment

- Package Version: 1.3.0
- Browser: Chrome
- OS: Windows
- Node version (`node -v`): 10.15.3
- Other:

**Comment by dpollastrini** [comment]
Confirmed this is an issue with "ng build --prod --aot" with Angular 8.x. Temporarily reverting to @okta/okta-angular 1.0.2 (working in another project) as a workaround.

**Comment by swiftone** [comment]
Internal Ref: OKTA-267219

**Comment by edesr1988** [comment]
Having the same issue after updating to 1.3.0. with ng build --prod --aot

**Comment by TonyGregg** [comment]
> 
> 
> Confirmed this is an issue with "ng build --prod --aot" with Angular 8.x. Temporarily reverting to @okta/okta-angular 1.2.2 (working in another project) as a workaround.

Hey, I am facing the same issue. How did you switch to okta-angular 1.2.2?

**Comment by dlevkov** [comment]
> > Confirmed this is an issue with "ng build --prod --aot" with Angular 8.x. Temporarily reverting to @okta/okta-angular 1.2.2 (working in another project) as a workaround.
> 
> Hey, I am facing the same issue. How did you switch to okta-angular 1.2.2?

Npm i - S @okta/okta-angular@1.2

**Comment by krishtgkk** [comment]
Any Idea if this is taken as priority and any timelines please

**Comment by krishtgkk** [comment]
Team I need PKCE flow to work and version 1.2.2 does not support it right. ( correct me if I am wrong ).

**Comment by sovushka-utrom** [comment]
I'm using "@angular/core": "8.0.0" and "@okta/okta-angular": "1.2.2" with PKCE set to true in config & it seems to work fine (how do you check it precisely?).   
Besides, I do have the same issue if I upgrade the package to 1.3.0.

**Comment by amracel** [comment]
I'm having the same problem with nodejs 12.12.0, angular 8.2.13, and both okta-angular 1.2.2 and 1.30.

**Comment by Zzarek** [comment]
This is a problem for me as well. Im basically stuck and cant release my software. 

I'm on 1.2.2

**Comment by swiftone** [comment]
We are testing changes to fix the AOT (and Angular 9) now, an update is coming Soon™️

**Comment by swiftone** [comment]
`@okta/okta-angular` v1.3.1 has been released that should fix support for AOT compilation (it also supports Angular 9).  Props to @aarongranick-okta for prioritizing and fixing the issue.  

If anyone continues to encounter problems, please open a new issue with details.
